id = "deep-slate-theme"
name = "Deep Slate"
version = "0.1.1"
schema_version = 1
authors = ["Roter-S"]
description = "A dark theme with deep blue-gray tones"
repository = "https://github.com/Roter-S/deep-slate-vscode"
